apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: test.paleobiogeography.org # what the certificate is good for
  dnsNames: # all the different domains that must be associated with the cert
    - test.paleobiogeography.org
    - www.test.paleobiogeography.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-multi.com
          - www.k8s-multi.com
